autosubmit: true
default:
  players: 'felix,mimi'
  color: GREEN
ui:
  card:
    h: 100
  container:
    padding: 0
    h: 130
  containertitle:
    left: 16
    bottom: 1
  minicard:
    h: 40
  minicontainer:
    padding: 0
    h: 130
games:
  a_game:
    friendly: Simple
    logo: bear
    color: gold
    options:
      gamemode: 'solo,hotseat,multi'
      handsize: '7,3,10'
    ploptions:
      level: '1,2,3,4,5,6,7'
      playmode: 'bot,human'
  accuse:
    friendly: 'J''Accuse'
    logo: backhand_index_pointing_down
    color: navy
    defaulthandsorting: none
    options:
      gamemode: 'hotseat,multi,solo'
      rounds: '1,2,6,4'
      stability: '2,3,4,5'
      handsize: '4,6,7,5'
      cardtype: 'c52,num'
      consensus: 'coupdetat,policy'
      colors: '4,3,2'
      empty_vote: 'add policy'
      defected: remove
    ploptions:
      level: '1,2,3,4,5,6,7'
      playmode: 'bot,human'
  aristo:
    friendly: Aristocracy
    logo: crown
    color: indigo
    defaulthandsorting: none
    options:
      church: 'no,yes'
      journey: 'no,yes'
      commission: 'no,yes'
      peasants: 'no,yes'
      rumors: 'no,yes'
    game_type: turn
    def_startlevel: 4
    achieve_inc: 0
    hand_size: 7
    farm_size: 4
    estate_size: 5
    chateau_size: 6
    ploptions:
      level: '1,2,3,4,5,6,7'
      playmode: 'bot,human'
  badger:
    friendly: Badger
    logo: badger
    color: maroon
    game_type: race
    ploptions:
      playmode: 'bot,human'
      handicap: '1,2,3'
    options:
      botmin: '500,1000,3000,5000'
      botmax: '1000,3000,6000,10000'
      gamemode: 'solo,multi'
    name: badger
  bluff:
    friendly: Bluff
    logo: beaming_face_with_smiling_eyes
    color: red
    defaulthandsorting: rank
    options:
      min_handsize: '1,3,2'
      max_handsize: '3,4,5,6,7'
    ploptions:
      playmode: 'bot,human'
  dinogame:
    friendly: Dino
    logo: sauropod
    color: orange
    game_type: race
    ploptions:
      playmode: 'bot,human'
      handicap: '1,2,3'
    options:
      botmin: '500,1000,2000,3000'
      botmax: '1000,3000,5000,8000'
      gamemode: 'solo,multi'
    name: dinogame
  dodogame:
    friendly: Dodogame
    logo: dodo
    color: darkslateblue
    game_type: race
    ploptions:
      playmode: 'bot,human'
      handicap: '1,2,3'
    options:
      botmin: '500,1000,2000,3000'
      botmax: '1000,3000,5000,8000'
      gamemode: 'solo,multi'
    name: dodogame
  button97:
    friendly: YesNo
    logo: camel
    color: steelblue
    game_type: race
    ploptions:
      playmode: 'bot,human'
    options:
      gamemode: 'solo,multi'
  button98:
    friendly: Simple
    logo: bear
    color: skyblue
    game_type: race
    ploptions:
      playmode: 'bot,human'
    options:
      gamemode: 'solo,multi'
  button99:
    friendly: Button
    logo: frog
    color: lightskyblue
    game_type: race
    ploptions:
      playmode: 'bot,human'
    options:
      gamemode: 'solo,multi'
  lacuna:
    friendly: lacuna
    logo: accordion
    color: water
    ploptions:
      playmode: 'bot,human'
    options:
      numPoints: '70,49,28'
      numColors: '10,7,4'
      numMeeples: '9,6,3'
      gamemode: 'solo,multi'
  fishgame:
    friendly: tier
    logo: leopard
    color: water
    ploptions:
      playmode: 'bot,human'
    options:
      numCards: '6,9,15,12'
      gamemode: 'solo,multi'
  fritz:
    friendly: 'A L''Honneur!'
    logo: fencing
    color: midnightblue
    defaulthandsorting: suit
    options:
      gamemode: 'solo,hotseat,multi'
      handsize: '9,11,13,10'
      cycles: '3,2,1'
      seconds_per_game: '600,60,180,120'
      seconds_per_move: '10,3,4,5'
      jokers: '3,2,1,0'
      overlapping: 'yes,no'
      jokers_per_group: '3,2,1'
    ploptions:
      playmode: 'bot,human'
      strategy: 'clairvoyant,random'
  feedback:
    friendly: Feedback
    logo: dragon
    color: BLUEGREEN
    options:
      gamemode: 'solo,hotseat,multi'
      poll: '200,2000,500,1000,3000'
      auto_weiter: 'no,yes'
    ploptions:
      level: '1,2,3,4,5,6,7'
      playmode: 'bot,human'
  ferro:
    friendly: Ferrocarril
    logo: train
    color: sienna
    defaulthandsorting: rank
    options:
      gamemode: 'solo,hotseat,multi'
      handsize: '3,5,11'
      coins: '3,5,10'
      maxrounds: '1,3,5,7'
      phase_order: 'fixed,anti,choice'
      thinking_time: '3,20,5,10'
      auto_weiter: 'no,yes'
    ploptions:
      playmode: 'bot,human'
      strategy: 'clairvoyant,random'
  emoticount:
    friendly: Emocount
    logo: abacus
    color: violet
    options:
      gamemode: 'solo,hotseat,multi'
      min: '2,3,4'
      max: '5,6,7'
    ploptions:
      playmode: 'bot,human'
      strategy: 'clairvoyant,random'
  huti:
    friendly: Chapeau
    logo: top_hat
    color: orange
    defaulthandsorting: rank
    options:
      gamemode: 'solo,hotseat,multi'
      handsize: '3,5,11,1'
    ploptions:
      level: '1,2,3,4,5,6,7'
      playmode: 'bot,human'
  nations:
    friendly: Nations
    logo: world_map
    color: indigo
    game_type: turn
    options:
      gamemode: 'solo,multi,hotseat'
      min_handsize: '1,3,2'
      max_handsize: '4,5,6,7'
    ploptions:
      playmode: 'bot,human'
      strategy: 'clairvoyant,random'
  setgame_old:
    friendly: Set
    logo: flamingo
    color: pink
    game_type: race
    ploptions:
      level: '1,2,3,4,5,6,7'
      playmode: 'bot,human'
    options:
      use_level: 'no,yes'
      numCards: '6,9,15,12'
      gamemode: 'solo,hotseat,multi'
  setgame:
    friendly: Set
    logo: flamingo
    color: pink
    game_type: race
    ploptions:
      playmode: 'bot,human'
      countdown: '12,10,8,7,5,3,2,1,0'
      hint: '2,1,0'
    options:
      deck_size: '12,15,30,81'
      grid_size: '3x3,4x4,5x4,4x3'
      special_set: '2,1,0'
      use_levels: 'no,yes'
      botmin: '1000,3000,4000,5000'
      botmax: '4000,6000,8000,10000'
    name: setgame
  sheriff:
    friendly: Sheriff
    logo: police_officer
    color: sienna
    game_type: turn
    options:
      gamemode: 'solo,hotseat,multi'
      min_handsize: '1,3,2'
      max_handsize: '4,5,6,7'
    ploptions:
      playmode: 'bot,human'
      strategy: 'clairvoyant,random'
  simplegame:
    friendly: Simple
    logo: frog
    color: sienna
    game_type: turn
    options:
      gamemode: 'solo,hotseat,multi'
      min_handsize: '1,3,2'
      max_handsize: '4,5,6,7'
    ploptions:
      playmode: 'bot,human'
      strategy: 'clairvoyant,random'
  spotit:
    friendly: Spotit
    logo: detective
    color: green
    game_type: race
    options:
      winning_score: '5,10,20,25'
      adaptive: 'no,yes'
      num_cards: '4,3,2'
      num_symbols: '4,12,10,8'
      max_count: '14,17,22'
    ploptions:
      playmode: 'bot,human'
  spotit_old:
    friendly: Spotit
    logo: detective
    color: green
    game_type: race
    options:
      adaptive: 'no,yes'
      use_levels: 'no,yes'
      zen_mode: 'no,yes'
      winning_score: '5,10,20,25'
      vocab: 'animals,objectPlus,lifePlus'
      num_cards: '3,2'
      num_symbols: '4,12,17,7'
    ploptions:
      level: '1,2,3,4,5,6,7'
      playmode: 'bot,human'
    rows: 3
    cols: 2
    min_scale: 0.75
    max_scale: 1.25
    num_cards: 2
    def_startlevel: 4
    levels:
      - { cols: 1, rows: 2 }
      - { rows: 2 }
      - { cols: 1 }
      - { cols: 1, rows: 4 }
      - { min_scale: 0.75, max_scale: 1.25 }
      - { cols: 1, rows: 5 }
      - { rows: 4 }
      - { cols: 3, rows: 5 }
      - { rows: 5 }
      - { rows: 6 }
      - { cols: 3, rows: 6 }
    winnerslist: []
  wise:
    friendly: Wise
    logo: owl
    color: gold
    options:
      gamemode: 'solo,hotseat,multi'
      winning_score: '1,5,10,20'
      strategy: 'clairvoyant,random'
    ploptions:
      level: '1,2,3,4,5,6,7'
      playmode: 'bot,human'
themes:
  jungle:
    color: '#2f7532'
    name: jungle
    texture: ../assets/texwall/leaves.jpeg
    bgBlend: overlay
    bgRepeat: no-repeat
    bgSize: cover
    fg: white
    bgImage: 'url("http://127.0.0.1:51700/assets/texwall/leaves.jpeg")'
  flow:
    color: '#006c7f'
    name: flow
    texture: ../assets/texwall/marble_blue2.jpeg
    bgBlend: normal
    bgRepeat: no-repeat
    bgSize: cover
  marble:
    color: '#e6be8a'
    name: marble
    texture: ../assets/texwall/marble_beige1.jpeg
    bgBlend: normal
    bgRepeat: no-repeat
    bgSize: cover
  ferien:
    color: '#2a52be'
    name: ferien
    texture: ../assets/texwall/meer.jpg
    bgBlend: normal
    bgRepeat: no-repeat
    bgSize: cover
    fg: white
    bgImage: 'url("http://127.0.0.1:51700/assets/texwall/meer.jpg")'
  dreamy:
    color: '#ffe4e1'
    name: dreamy
    texture: ../assets/texwall/marble_rosa.jpeg
    bgBlend: normal
    bgRepeat: no-repeat
    bgSize: cover
  amethyst:
    color: '#4c2882'
    name: amethyst
    texture: ../assets/texwall/marble_violet1.jpeg
    bgBlend: luminosity
    bgRepeat: no-repeat
    bgSize: cover
  cave:
    color: '#002e63'
    name: cave
    texture: ../assets/texwall/marble_blue1.jpeg
    bgBlend: normal
    bgRepeat: no-repeat
    bgSize: cover
  water:
    color: '#2771c9'
    texture: ../assets/texwall/water.jpg
    bgBlend: normal
    bgRepeat: no-repeat
    bgSize: cover
    fg: '#ffffff'
    name: water
    bgImage: 'url("http://127.0.0.1:51700/assets/texwall/water.jpg")'
  forest:
    color: '#046307'
    texture: ../assets/texwall/wald.jpg
    bgBlend: overlay
    bgRepeat: no-repeat
    bgSize: cover
    name: forest
    fg: white
    bgImage: 'url("http://127.0.0.1:51700/assets/texwall/wald.jpg")'
  gold:
    color: '#fff000'
    texture: ../assets/texwall/marble_violet1.jpeg
    bgBlend: darken
    bgRepeat: no-repeat
    bgSize: cover
    name: gold
  pullover:
    color: 'rgb(77, 127, 179)'
    texture: ../assets/texrepeat/argyle_78_70.png
    bgBlend: luminosity
    bgRepeat: repeat
    bgSize: auto
    name: pullover
  caramel:
    name: caramel
    color: 'rgb(177, 115, 4)'
    fg: white
    bgBlend: multiply
    bgRepeat: no-repeat
    bgSize: cover
    texture: ../assets/texwall/marble_gold.jpeg
userlist:
  - amanda
  - annabel
  - diana
  - felix
  - guest
  - gul
  - lauren
  - mac
  - mimi
  - nasi
  - sarah
  - sheeba
  - valerie
  - wolferl
texturelist:
  - wood-001.png
  - wood-002.png
  - wood-003.png
  - wood-004.png
  - wood-005.png
  - marble_beach.JPG
  - marble_beige1.jpeg
  - marble_beigegruen.jpeg
  - marble_blaugold.jpeg
  - marble_blue.jpeg
  - marble_blue1.jpeg
  - marble_blue2.jpeg
  - marble_blue3.jpeg
  - marble_dark.jpeg
  - marble_gold.jpeg
  - marble_green1.jpeg
  - marble_greenorange.jpeg
  - marble_grey1.jpeg
  - marble_grey2.jpeg
  - marble_grey3.jpeg
  - marble_meer1.jpg
  - marble_red.jpeg
  - marble_rosa.jpeg
  - marble_rosagrau.jpeg
  - marble_violet1.jpeg
  - marble_water.jpg
  - marble_weiss1.jpeg
  - marble_weiss2.jpeg
  - marble_weiss3.jpeg
  - marble_weiss4.jpeg
  - vg2wall.png
  - wall1.jpg
  - wall2.jpg
  - wall3.JPG
  - wall4.jpg
  - wall5.jpg
  - wall6.JPG
  - wood1.png
texturelistnew:
  - ttransargyle.png
  - black-felt.png
  - black-linen.png
  - brushed-alum.png
  - clean-textile.png
  - dark-mosaic.png
  - escheresque.png
  - fabric-plaid.png
  - fabric0.jpg
  - felt.png
  - pool-table.png
  - scribble-light.png
  - soft-kill.png
  - stitched-wool.png
  - stucco.png
  - subtle-carbon.png
  - subtle-grey.png
  - subtle-grunge.png
  - tileable-wood-colored.png
  - tileable-wood.png
  - translucent-fibres.png
  - tweed.png
  - velvet.png
  - vg3.png
  - white-sand.png
  - xv.png
